dist: trusty
sudo: required

language: node_js

env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null

matrix:
  fast_finish: true
  allow_failures:
    - env: NODE_SCRIPT="tests/run_e2e.js --nightly"
    - env: NODE_SCRIPT="tests/run_e2e.js --ng2"
    - env: DEPLOY_SCRIPT="scripts/git-builds.js"
    - node_js: "7"
  include:
    - node_js: "6"
      os: linux
      env: SCRIPT=lint
    - node_js: "6"
      os: linux
      env: SCRIPT=build
    - node_js: "6"
      os: linux
      env: SCRIPT=test
    - node_js: "6"
      os: linux
      env: NODE_SCRIPT="tests/run_e2e.js --glob=tests/build/**"
    - node_js: "6"
      os: linux
      env: NODE_SCRIPT="tests/run_e2e.js --ignore=**/tests/build/**"
    - node_js: "6"
      os: linux
      env: NODE_SCRIPT="tests/run_e2e.js --eject --glob=tests/build/**"

    # Deploy builds.
    - node_js: "6"
      os: linux
      env:
        - DEPLOY_SCRIPT="scripts/git-builds.js"
        # GITHUB_TOKEN_ANGULAR=<github token, a personal access token of the angular-builds account, account access in valentine>
        # This is needed for the e2e Travis matrix task to publish packages to github for continuous packages delivery.
        - secure: hm9rsprVFwU2xweRLTatPvigDLueIdSnteAo1i1flSKnODx0uCmuXgyGlqhDsXHlCyZBltzKnzhRlu1i+nurUNSNQcgBszD8qROCutGdii6jnFjhA/VpwgM0sYkRWy/2RV5Sta2I/fsLHUIzcdQrmGPzb6mX+8VNa7oXO2Oo4BABtHGc+5KlZN/4thWEfczop9d0/JFK9pNYYwFN71xcQhL+zlMQvOb20JDAGgff8jWbUJ5VwXJsrHgNr3RHnQM46ypDOZSnRHXYQr4jl1E/1V6N8u7aFpLyXhw5KliR9FE1nMl7dim+/XxUe9pmw5jAygOkynB9KHKZFsyYQ67YIpM+8ww+Sz9C7pFwDhfvBv/snuRUhGNeHChuoCuGaUpcAoiknIVK6Eavm86925bFpp/hI8J43xwQ0FkGMnS01D2t0JAAs2tjRC6ot4v3QDHhfhbfaaf2fgVN2CqJZxQgopq7n1thDI6LE43CeqNpKvkJzTEjRQMvSkm6WQ/t6EwcQzj2qOzQzwKoJd1gFc1BEJyjBkPynrjn9rfi2TIUF26JYVhuKE6cjmFdHwr/ZbxZwkzOIQE5ZmZ+N0IVUUZ02ChJpT22JuAIZmM9VG4vbDfPsNxUN6IhF9gkLL20j69UHf+p0vOxbs1qlxKx1av0iRceTzZz1Jgwzj7/w7Hj0fE=

    # Optional builds.
    - node_js: "6"
      os: linux
      env: NODE_SCRIPT="tests/run_e2e.js --ng2"
    - node_js: "6"
      os: linux
      env: NODE_SCRIPT="tests/run_e2e.js --nightly"
    - node_js: "7"
      os: linux
      env: NODE_SCRIPT=tests/run_e2e.js

before_install:
  # Use a virtual display.
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  # Install latest chrome.
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CHROME_BIN=/usr/bin/google-chrome; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libappindicator1 fonts-liberation; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo dpkg -i google-chrome*.deb; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "--no-sandbox" > ~/.config/chrome-flags.conf; fi
  # Install yarn.
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn config set spin false
  - yarn config set progress false

script:
  - if [[ "$SCRIPT" ]]; then npm run-script $SCRIPT; fi
  - if [[ "$NODE_SCRIPT" ]]; then node $NODE_SCRIPT; fi
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" && "$DEPLOY_SCRIPT" != "" ]]; then node $DEPLOY_SCRIPT; fi
